# Extends the mainnet preset
PRESET_BASE: $PRESET_BASE
CONFIG_NAME: testnet # needs to exist because of Qrysm. Otherwise it conflicts with mainnet genesis

# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: $NUMBER_OF_VALIDATORS
#HUMAN_TIME_PLACEHOLDER
MIN_GENESIS_TIME: $GENESIS_TIMESTAMP
GENESIS_FORK_VERSION: $GENESIS_FORK_VERSION
GENESIS_DELAY: $GENESIS_DELAY

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT: $SLOT_DURATION_IN_SECONDS
SECONDS_PER_EXECUTION_BLOCK: $SLOT_DURATION_IN_SECONDS
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: $MIN_VALIDATOR_WITHDRAWABILITY_DELAY
SHARD_COMMITTEE_PERIOD: $SHARD_COMMITTEE_PERIOD
EXECUTION_FOLLOW_DISTANCE: $EXECUTION_FOLLOW_DISTANCE
SLOTS_PER_EPOCH: $SLOTS_PER_EPOCH
MAX_SEED_LOOKAHEAD: $MAX_SEED_LOOKAHEAD
EPOCHS_PER_EXECUTION_VOTING_PERIOD: $EPOCHS_PER_EXECUTION_VOTING_PERIOD

# Validator cycle
# ---------------------------------------------------------------
INACTIVITY_SCORE_BIAS: $INACTIVITY_SCORE_BIAS
INACTIVITY_SCORE_RECOVERY_RATE: $INACTIVITY_SCORE_RECOVERY_RATE
EJECTION_BALANCE: $EJECTION_BALANCE
MIN_PER_EPOCH_CHURN_LIMIT: $MIN_PER_EPOCH_CHURN_LIMIT
CHURN_LIMIT_QUOTIENT: $CHURN_LIMIT_QUOTIENT
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: $MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT

# Withdrawals
# ---------------------------------------------------------------
MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP: $MAX_VALIDATORS_PER_WITHDRAWALS_SWEEP

# Fork choice
# ---------------------------------------------------------------
PROPOSER_SCORE_BOOST: $PROPOSER_SCORE_BOOST
REORG_PARENT_WEIGHT_THRESHOLD: $REORG_PARENT_WEIGHT_THRESHOLD
REORG_MAX_EPOCHS_SINCE_FINALIZATION: $REORG_MAX_EPOCHS_SINCE_FINALIZATION

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: $CHAIN_ID
DEPOSIT_NETWORK_ID: $CHAIN_ID
DEPOSIT_CONTRACT_ADDRESS: $DEPOSIT_CONTRACT_ADDRESS
